@startuml
actor User as u
entity Extension as e
entity Server as s
entity CRM_Plat as crm

group All RingCentral logic is handled by Embeddable
end

group CRM Auth
    u -> e: click Auth button (not for Pipedrive though)
    e -> s: Auth
    s -> crm: Auth
    crm -> s: user info
    s -> e: jwt
end

group GET POST Call/Message log, Contact
    u -> e: fill in form
    e -> s: rc data + form data
    s -> crm: API calls
    crm -> s: returned CRM data
    s -> e: signal success/fail
end
@enduml