@startuml
start

:Call Initiated;
if (Auto Log?) then (Yes)
  :Call Connects (SSCL);
  note right
    [AUTO - CREATE log]
    Data: a few fields
  end note

  :Call Ends (SSCL);
  note right
    [AUTO - UPDATE log]
    Data: most fields except accurate duration, recording link etc.
  end note

  :Call Record Available in Call History;

    if(Can go in parallel) then ( )
        :User can perform disposition;
        note right
          [MANUAL - UPSERT call disposition]
          Data: agent notes, associations etc
        end note
    else ( )
        :Call data fully ready (SSCL);
        note right
          [AUTO - UPDATE log]
          Data: accurate duration, recording link etc.
        end note
    endif


else (No)
  :Call Ends;
  :Call Record Available in Call History;
    if(Can go in parallel) then ( )
        :User can perform logging and disposition;
        note right
          [MANUAL - UPSERT call logging and disposition]
          Data: agent notes, associations etc
        end note
    else ( )
        :Call data fully ready;
        note right
          [AUTO - UPDATE log if exists]
          Data: accurate duration, recording link etc.
        end note
    endif
endif

stop
@enduml
