!!! tip "This documentation is a PREVIEW only"
    The Unified CRM extension is preparing to release a new developer framework allowing developers to build and deploy custom adapters for any arbitrary CRM. During this preview you will notice the following, all of which will be resolved soon.

    * Unresolved "TODO" items in the documentation
    * References to code samples may appear blank
    
<!--
!!! tip "The developer framework is currently in BETA"
    This framework is in beta. Please [submit a Github issue](https://github.com/ringcentral/rc-unified-crm-extension/issues) if you encounter any problems or have a question.
-->