!!! tip "This documentation is a PREVIEW only"
    The Unified CRM extension is preparing to release a new developer framework allowing developers to build and deploy custom adapters for any arbitrary CRM.
    
<!--
!!! tip "The developer framework is currently in BETA"
    This framework is in beta. Please [submit a Github issue](https://github.com/ringcentral/rc-unified-crm-extension/issues) if you encounter any problems or have a question.
-->