@startuml
start
:A phone call;
:The call ends;
if (Log call) then (yes)
    :Call log is created without accurate result, duration and (if applicable) recording link;
    :Call result and duration are sent to updateCallLog API;
    :(If applicable) Call recording is sent to updateCallLog API;
else (no)
    :After a few seconds;
    :Result & duration are ready;
    if(Log call) then (yes)
        :Call log is created without (if applicable) recording link;
        :(If applicable) Call recording is sent to updateCallLog API;
    else (no)
        :After a few seconds to a few minutes;
        :Call recording is ready;
        :Log call;
        :Call log is created with all data;
    endif
endif
:Done;
stop
@enduml